<?php
$admin = array(
        'basePath'      => 'http://localhost/admin',
        'projeto'       => 'Gael',
        'controladores' => array(
        array(
            'nome'      => 'cases',
            'models'    => array('cases', 'projetos'),
            'model'     => 'cases',
            'closures'  => array(
                              array( 'metodo'         => array('post', 'get'),
                                     'acao'           => 'criar',
                                     'url'            => '/admin/cases/novo',
                                     'params_closure' => array(),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Cadastrar cases',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'titulo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Título',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
															array(
                                                                 'nome'       => 'descricao',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Subtítulo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'texto',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Texto',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),															
                                                            array(
                                                                 'nome'       => 'imagem_thumb',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_thumb_over',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb Hover',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_integra',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem na íntegra',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'ativo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Ativo/Inativo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao salvar case',
                                                                  ),
                                                        ),
                              ),

                              array( 'metodo'         => 'post',
                                     'acao'           => 'editar',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Editar cases',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'path',
                                                            ),
                                                            array(
                                                                 'nome'       => 'titulo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Título',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'descricao',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Subtítulo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'texto',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Texto',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_thumb',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
															array(
                                                                 'nome'       => 'imagem_thumb_over',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb Over',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_integra',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem na íntegra',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'ativo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Ativo/Inativo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao editar case',
                                                                  ),
                                                        ),
                              ),

                              array( 'metodo'         => 'delete',
                                     'acao'           => '',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Remover case',
                                     'params_request' => array ( 
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao remover case',
                                                                  ),
                                                        ),
                                     'template' => array(
                                                        'titulo' => 'Remover case',
                                                   ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'todos',
                                     'url'            => '/admin/cases',
                                     'params_closure' => array(),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Listagem de cases',
                                     'params_request' => array ( 
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao salvar case',
                                                                  ),
                                                        ),
                                     'template' => array(
                                                        'titulo' => 'Listagem de cases',
                                                   ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'unico',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Busca case pelo id',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao buscar case',
                                                                  ),
                                                        ),
                              ),
                          ),
               ),

               array(
                    'nome'      => 'home',
                    'models'    => array('cases', 'projetos'),
                    'model'     => 'cases',
                    'closures'  => array(
                                      array( 'metodo'         => 'get',
                                             'url'            => '/admin/home',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'cases', 'projetos'),
                                             'descricao'      => 'Home',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao acessar home',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Home',
                                                           ),
                                             'nome_rota'     => 'home',
                                      ),
                                  ),
                  ),

				array(
                    'nome'      => 'destaques',
                    'models'    => array('destaques', 'projetos'),
                    'model'     => 'destaques',
                    'closures'  => array(
                                      array( 'metodo'         => array('post', 'get'),
                                             'acao'           => 'criar',
                                             'url'            => '/admin/destaques/novo',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Cadastrar destaque',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'titulo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Título',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'link',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Link',
                                                                         'required'   => 'false',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'imagem',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'Imagem',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'thumb',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'Hover',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),																
                                                                    array(
                                                                         'nome'       => 'ativo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Ativo/Inativo',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao salvar case',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'post',
                                             'acao'           => 'editar',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Editar destaque',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'path',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'titulo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Título',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'link',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Link',
                                                                         'required'   => 'false',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'imagem',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'BG',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'thumb',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'Hover',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'ativo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Ativo/Inativo',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao editar destaque',
                                                                          ),
                                                                ),
                                      ),					
                                      array( 'metodo'         => 'get',
                                             'acao'           => 'todos',
                                             'url'            => '/admin/destaques',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Listagem de destaques',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao acessar destaques',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Listagem de destaques',
                                                           ),
                                      ),

                                      array( 'metodo'         => 'get',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Busca destaque pelo id',
                                             'params_request' => array (
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao buscar destaque',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'delete',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques'),
                                             'descricao'      => 'Remover destaque',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao remover destaque',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Remover destaque',
                                                           ),
                                      ),
                                  ),
                  ), 

				array(
					'nome'      => 'contato',
					'models'    => array('contato', 'projetos'),
					'model'     => 'contato',
					'closures'  => array(
                              array( 'metodo'         => 'post',
                                     'acao'           => 'editar',
                                     'url'            => '/admin/contato/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'contato', 'projetos'),
                                     'descricao'      => 'Editar contato',
                                     'params_request' => array (
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'path',
                                                            ),
                                                            array(
                                                                 'nome'       => 'contato_email',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Email',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'contato_fone',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Telefone',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'contato_endereco',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Endereço',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'video',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Vídeo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            )
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao editar contato',
                                                                  ),
                                                        ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'todos',
                                     'url'            => '/admin/contato',
                                     'params_closure' => array(),
                                     'params_use'     => array('app', 'contato', 'projetos'),
                                     'descricao'      => 'Listagem de contato',
                                     'params_request' => array ( 
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao salvar contato',
                                                                  ),
                                                        ),
                                     'template' => array(
                                                        'titulo' => 'Listagem de contato',
                                                   ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'unico',
                                     'url'            => '/admin/contato/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'contato', 'projetos'),
                                     'descricao'      => 'Busca contato pelo id',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao buscar contato',
                                                                  ),
                                                        ),
                              ),
                          ),
               ),
				  
			'controlador_aut'  => array(
                'closures'  => array(
                    array(   'metodo'         => array('post', 'get'),
                             'url'            => '/admin/login',
                             'params_closure' => array(),
                             'params_use'     => array('app'),
                             'descricao'      => 'Login',
                             'nickname'       => 'loginForm',
                             'params_request' => array (
                                                    array(
                                                             'nome'       => 'usuario',
                                                             'tipo'       => 'string',
                                                             'descricao'  => 'Usuário',
                                                             'required'   => 'true',
                                                             'param_type' => 'form',
                                                        ),
                                                    array(
                                                             'nome'       => 'senha',
                                                             'tipo'       => 'string',
                                                             'descricao'  => 'Senha',
                                                             'required'   => 'true',
                                                             'param_type' => 'form',
                                                        ),
                                                 ),
                             'response_messages' => array(
                                                    array('code'    => '500',
                                                          'message' => 'Problema ao efetuar login',
                                                          ),
                                                ),
                             'template' => array(
                                                'titulo' => 'Login',
                                           ),
                      ),
                    array(   'metodo'         => 'post',
                             'url'            => '/admin/logout',
                             'params_closure' => array(),
                             'params_use'     => array('app'),
                             'descricao'      => 'Logout',
                             'nickname'       => 'logoutForm',
                             'params_request' => array (
                                                 ),
                             'response_messages' => array(
                                                    array('code'    => '500',
                                                          'message' => 'Problema ao efetuar logout',
                                                          ),
                                                ),
                      ),
                ),
             ),
		)
      );

return $admin;