<?php
$admin = array(
        'basePath'      => 'http://localhost/admin',
        'projeto'       => 'Gael',
        'controladores' => array(
          array(
            'nome'      => 'cases',
            'models'    => array('cases', 'projetos'),
            'model'     => 'cases',
            'closures'  => array(
                              array( 'metodo'         => array('post', 'get'),
                                     'acao'           => 'criar',
                                     'url'            => '/admin/cases/novo',
                                     'params_closure' => array(),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Cadastrar cases',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'titulo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Título',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'descricao',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Descrição',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_thumb',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_integra',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem na íntegra',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'ativo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Ativo/Inativo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao salvar case',
                                                                  ),
                                                        ),
                              ),

                              array( 'metodo'         => 'post',
                                     'acao'           => 'editar',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Editar cases',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'path',
                                                            ),
                                                            array(
                                                                 'nome'       => 'titulo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Título',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'descricao',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Descrição',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_thumb',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem Thumb',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'imagem_integra',
                                                                 'tipo'       => 'File',
                                                                 'descricao'  => 'Imagem na íntegra',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'body',
                                                            ),
                                                            array(
                                                                 'nome'       => 'ativo',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Ativo/Inativo',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao editar case',
                                                                  ),
                                                        ),
                              ),

                              array( 'metodo'         => 'delete',
                                     'acao'           => '',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Remover case',
                                     'params_request' => array ( 
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao remover case',
                                                                  ),
                                                        ),
                                     'template' => array(
                                                        'titulo' => 'Remover case',
                                                   ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'todos',
                                     'url'            => '/admin/cases',
                                     'params_closure' => array(),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Listagem de cases',
                                     'params_request' => array ( 
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao salvar case',
                                                                  ),
                                                        ),
                                     'template' => array(
                                                        'titulo' => 'Listagem de cases',
                                                   ),
                              ),

                              array( 'metodo'         => 'get',
                                     'acao'           => 'unico',
                                     'url'            => '/admin/cases/:id',
                                     'params_closure' => array('id'),
                                     'params_use'     => array('app', 'cases', 'projetos'),
                                     'descricao'      => 'Busca case pelo id',
                                     'params_request' => array ( 
                                                            array(
                                                                 'nome'       => 'id',
                                                                 'tipo'       => 'string',
                                                                 'descricao'  => 'Id',
                                                                 'required'   => 'true',
                                                                 'param_type' => 'form',
                                                            ),
                                                         ),
                                     'response_messages' => array(
                                                            array('code'    => '500',
                                                                  'message' => 'Problema ao buscar case',
                                                                  ),
                                                        ),
                              ),
                          ),
               ),

               array(
                    'nome'      => 'home',
                    'models'    => array('cases', 'projetos'),
                    'model'     => 'cases',
                    'closures'  => array(
                                      array( 'metodo'         => 'get',
                                             'url'            => '/admin/home',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'cases', 'projetos'),
                                             'descricao'      => 'Home',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao acessar home',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Home',
                                                           ),
                                             'nome_rota'     => 'home',
                                      ),
                                  ),
                  ),

              array(
                    'nome'      => 'destaques',
                    'models'    => array('destaques', 'projetos'),
                    'model'     => 'destaques',
                    'closures'  => array(
                                      array( 'metodo'         => array('post', 'get'),
                                             'acao'           => 'criar',
                                             'url'            => '/admin/destaques/novo',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Cadastrar destaque',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'titulo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Título',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'link',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Link',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'imagem',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'Imagem',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'ativo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Ativo/Inativo',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao salvar case',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'post',
                                             'acao'           => 'editar',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Editar destaque',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'path',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'titulo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Título',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'link',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Link',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'imagem',
                                                                         'tipo'       => 'File',
                                                                         'descricao'  => 'Imagem',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'body',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'ativo',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Ativo/Inativo',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao editar destaque',
                                                                          ),
                                                                ),
                                      ),					
                                      array( 'metodo'         => 'get',
                                             'acao'           => 'todos',
                                             'url'            => '/admin/destaques',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Listagem de destaques',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao acessar destaques',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Listagem de destaques',
                                                           ),
                                      ),

                                      array( 'metodo'         => 'get',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques', 'projetos'),
                                             'descricao'      => 'Busca destaque pelo id',
                                             'params_request' => array (
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao buscar destaque',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'delete',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/destaques/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'destaques'),
                                             'descricao'      => 'Remover destaque',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao remover destaque',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Remover destaque',
                                                           ),
                                      ),
                                  ),
                  ), 

              array(
                    'nome'      => 'contatos',
                    'models'    => array('contatos', 'projetos'),
                    'model'     => 'contatos',
                    'closures'  => array(
                                      array( 'metodo'         => array('post', 'get'),
                                             'acao'           => 'criar',
                                             'url'            => '/admin/contatos/novo',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'contatos', 'projetos'),
                                             'descricao'      => 'Cadastrar contato',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'email',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Email',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'nome',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Nome',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'descricao',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Descrição',
                                                                         'required'   => 'false',
                                                                         'param_type' => 'form',
                                                                    )
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao salvar contato',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'post',
                                             'acao'           => 'editar',
                                             'url'            => '/admin/contatos/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'contatos', 'projetos'),
                                             'descricao'      => 'Editar destaque',
                                             'params_request' => array (
                                                                    array(
                                                                         'nome'       => 'email',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Email',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'nome',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Nome',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'descricao',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Descrição',
                                                                         'required'   => 'false',
                                                                         'param_type' => 'form',
                                                                    )
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao editar contato',
                                                                          ),
                                                                ),
                                      ),					
                                      array( 'metodo'         => 'get',
                                             'acao'           => 'todos',
                                             'url'            => '/admin/contatos',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'contatos', 'projetos'),
                                             'descricao'      => 'Listagem de contatos',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao acessar contatos',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Listagem de contatos',
                                                           ),
                                      ),

                                      array( 'metodo'         => 'get',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/contatos/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'contatos', 'projetos'),
                                             'descricao'      => 'Busca contatos pelo id',
                                             'params_request' => array (
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao buscar destaque',
                                                                          ),
                                                                ),
                                      ),									  
									  									  
                                      array( 'metodo'         => 'delete',
                                             'acao'           => '',
                                             'url'            => '/admin/contatos/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'contatos', 'projetos'),
                                             'descricao'      => 'Remover contato',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao remover contato',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Remover contato',
                                                           ),
                                      ),									  
                                  ),
                  ),

              array(
                    'nome'      => 'usuario',
                    'models'    => array('usuario', 'projetos'),
                    'model'     => 'usuario',
                    'closures'  => array(
                                      array( 'metodo'         => array('post', 'get'),
                                             'url'            => '/admin/esqueci-senha',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'usuario', 'projetos'),
                                             'descricao'      => 'Esqueci senha',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'email',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Email para recuperar a senha',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao enviar link para troca senha',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'get',
                                             'url'            => '/admin/troca-senha/:token',
                                             'params_closure' => array('token'),
                                             'params_use'     => array('app', 'usuario', 'projetos'),
                                             'descricao'      => 'Trocar senha',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'token',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'token de confirmação',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'path',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                        array('code'    => '500',
                                                                            'message' => 'Ocorreu um erro',
                                                                        ),
                                                                        array('code'    => '400',
                                                                            'message' => 'O usuário com token nnnn não foi encontrado.',
                                                                        ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'post',
                                             'url'            => '/admin/troca-senha',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'usuario', 'projetos'),
                                             'descricao'      => 'Trocar senha',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'token',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'token de confirmação',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'senha',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Senha',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'confirma-senha',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Confirmação da Senha',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                        array('code'    => '500',
                                                                            'message' => 'Problema ao trocar senha',
                                                                        ),
                                                                        array('code'    => '400',
                                                                            'message' => 'O usuário com token nnnn não foi encontrado.',
                                                                        ),
                                                                ),
                                      ),
									  array( 'metodo'         => 'post',
                                             'acao'           => 'editar',
                                             'url'            => '/admin/usuario/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'usuario', 'projetos'),
                                             'descricao'      => 'Editar usuário',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'path',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'nome',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Nome',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                    array(
                                                                         'nome'       => 'grupos',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Grupos',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao editar usuário',
                                                                          ),
                                                                ),
                                      ),
                                      array( 'metodo'         => 'get',
                                             'acao'           => 'unico',
                                             'url'            => '/admin/usuario/:id',
                                             'params_closure' => array('id'),
                                             'params_use'     => array('app', 'usuario'),
                                             'descricao'      => 'Busca usuário pelo id',
                                             'params_request' => array ( 
                                                                    array(
                                                                         'nome'       => 'id',
                                                                         'tipo'       => 'string',
                                                                         'descricao'  => 'Id',
                                                                         'required'   => 'true',
                                                                         'param_type' => 'form',
                                                                    ),
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao buscar usuário',
                                                                          ),
                                                                ),
                                      ),

                                      array( 'metodo'         => 'get',
                                             'acao'           => 'todos',
                                             'url'            => '/admin/usuario',
                                             'params_closure' => array(),
                                             'params_use'     => array('app', 'usuario'),
                                             'descricao'      => 'Listagem de usuários',
                                             'params_request' => array ( 
                                                                 ),
                                             'response_messages' => array(
                                                                    array('code'    => '500',
                                                                          'message' => 'Problema ao listar usuários',
                                                                          ),
                                                                ),
                                             'template' => array(
                                                                'titulo' => 'Listagem de usuários',
                                                           ),
                                      ),
                                  ),
                  ),
          ),

          'controlador_aut'  => array(
                'closures'  => array(
                    array(   'metodo'         => array('post', 'get'),
                             'url'            => '/admin/login',
                             'params_closure' => array(),
                             'params_use'     => array('app'),
                             'descricao'      => 'Login',
                             'nickname'       => 'loginForm',
                             'params_request' => array (
                                                    array(
                                                             'nome'       => 'usuario',
                                                             'tipo'       => 'string',
                                                             'descricao'  => 'Usuário',
                                                             'required'   => 'true',
                                                             'param_type' => 'form',
                                                        ),
                                                    array(
                                                             'nome'       => 'senha',
                                                             'tipo'       => 'string',
                                                             'descricao'  => 'Senha',
                                                             'required'   => 'true',
                                                             'param_type' => 'form',
                                                        ),
                                                 ),
                             'response_messages' => array(
                                                    array('code'    => '500',
                                                          'message' => 'Problema ao efetuar login',
                                                          ),
                                                ),
                             'template' => array(
                                                'titulo' => 'Login',
                                           ),
                      ),
                    array(   'metodo'         => 'post',
                             'url'            => '/admin/logout',
                             'params_closure' => array(),
                             'params_use'     => array('app'),
                             'descricao'      => 'Logout',
                             'nickname'       => 'logoutForm',
                             'params_request' => array (
                                                 ),
                             'response_messages' => array(
                                                    array('code'    => '500',
                                                          'message' => 'Problema ao efetuar logout',
                                                          ),
                                                ),
                      ),
                ),
             ),
      );

return $admin;
